name: DevOps GitHub Actions CI-CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # १. गिटहबवरून लेटेस्ट कोड घेऊन येणे
    - name: Checkout Code
      uses: actions/checkout@v4

    # २. डॉकर हब मध्ये लॉगइन करणे
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # ३. डॉकर इमेज इमेज बिल्ड करणे आणि पुश करणे
    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-devops-app:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-devops-app:latest

    # ४. AWS EC2 सर्व्हरवर नवीन इमेज डिप्लॉय करणे
    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ubuntu
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        script: |
          docker stop my-web-app || true
          docker rm my-web-app || true
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-devops-app:latest
          docker run -d --name my-web-app -p 80:3000 ${{ secrets.DOCKERHUB_USERNAME }}/my-devops-app:latest
